--!strict
-- Textes fixes visibles par le joueur (source EN pour AutoLocalize Roblox).
-- Ne pas y mettre : noms de joueurs, nombres seuls, identifiants techniques.

local LocalizationStrings = {
	-- Pancarte tutoriel lobby
	HowToPlayTitle = "HOW TO PLAY",
	HowToPlayLine1 = "1. Enter the Bubble Room",
	HowToPlayLine2 = "2. Pop bubbles to fill your backpack",
	HowToPlayLine3 = "3. Return to the lobby",
	HowToPlayLine4 = "4. Sell your bubbles for coins",
	HowToPlayLine5 = "5. Upgrade and pop even more!",

	-- Classement
	TopCoinCollectors = "TOP COIN COLLECTORS",
	GlobalLeaderboard = "GLOBAL LEADERBOARD",
	Rank = "RANK",
	Player = "PLAYER",
	Coins = "COINS",
	LoadingLeaderboard = "Loading leaderboard...",
	NoRankingsYet = "No rankings yet",
	LeaderboardUnavailable = "Leaderboard temporarily unavailable",
	LeaderboardUnavailableStudio = "Leaderboard unavailable in Studio",
	LeaderboardStudioPreview = "Studio preview — local players only",

	-- Kiosque vente
	SellYourBubbles = "SELL YOUR BUBBLES",
	PopFillCashIn = "POP · FILL · CASH IN",
	BagValue = "Bag value:",
	CoinsUnit = "coins",
	Terminal = "TERMINAL",
	StepOnThePad = "Step on the pad",
	ThenSell = "then SELL",
	TurnBubblesIntoCoins = "Turn your bubbles into coins!",

	-- Boutique
	BubbleShop = "BUBBLE SHOP",
	ShopSign = "SHOP",
	BuyBubblesAndItems = "BUY BUBBLES & ITEMS",
	BuyCoolItems = "Buy cool items to boost your adventure!",
	OpenShop = "Open Shop",
	ShopObject = "Bubble Shop",
	BrowseSkills = "Browse Skills",
	BrowseItems = "Browse Items",
	BrowseCosmetics = "Browse Cosmetics",
	Upgrades = "Upgrades",
	Skills = "Skills",
	Items = "Items",
	Cosmetics = "Cosmetics",
	Buy = "Buy",
	Upgrade = "Upgrade",
	ComingSoon = "Coming Soon",
	Locked = "Locked",
	TooExpensive = "Too Expensive",
	Inventory = "Inventory",
	Equip = "Equip",
	Equipped = "Equipped",
	Unequip = "Unequip",
	Owned = "Owned",
	DefaultBackpack = "Default Backpack",
	GoldBackpack = "Gold Backpack",
	EmeraldBackpack = "Emerald Backpack",
	NeonBackpack = "Neon Backpack",
	BackpackGoldDesc = "Golden style with extra bubble capacity.",
	BackpackEmeraldDesc = "Emerald style with extra bubble capacity.",
	BackpackNeonDesc = "Neon style with extra bubble capacity.",
	SkillSpeed = "Speed",
	SkillSpeedDesc = "Move faster across the bubble grid.",
	SkillJump = "Jump",
	SkillJumpDesc = "Jump higher to reach more bubbles.",
	SkillPower = "Power",
	SkillPowerDesc = "Pop bubbles in a wider radius.",
	SkillCoinMult = "Coin Multiplier",
	SkillCoinMultDesc = "Earn more coins from every sale.",
	SkillMagnet = "Magnet",
	SkillMagnetDesc = "Pull nearby bubbles toward you. Coming soon!",
	SkillLuck = "Luck",
	SkillLuckDesc = "Better odds on rare finds. Coming soon!",
	SkillCapacityBoost = "Capacity Boost",
	SkillCapacityBoostDesc = "Carry even more bubbles at once. Coming soon!",
	ItemPin = "Pin",
	ItemPinDesc = "Pop bubbles in a cross pattern. Shop item coming soon!",
	ItemHammer = "Hammer",
	ItemHammerDesc = "Crush a 3×3 area around you. Shop item coming soon!",
	ItemMultiPopTool = "Multi Pop Tool",
	ItemMultiPopToolDesc = "Chain pops across multiple bubbles. Coming soon!",
	ItemSpecialTool = "Special Tool",
	ItemSpecialToolDesc = "A powerful surprise tool. Coming soon!",
	CosmeticCap = "Cap",
	CosmeticCapDesc = "A stylish cap for your avatar. Coming soon!",
	CosmeticHat = "Hat",
	CosmeticHatDesc = "Stand out with a fun hat. Coming soon!",
	CosmeticVest = "Vest",
	CosmeticVestDesc = "Layer up with a cool vest. Coming soon!",
	CosmeticShirt = "Shirt",
	CosmeticShirtDesc = "Fresh shirt styles for your look. Coming soon!",
	CosmeticAccessory = "Accessory",
	CosmeticAccessoryDesc = "Extra flair for your avatar. Coming soon!",
	CapacityLabel = "Capacity",
	SellBeforeSwitch = "Sell bubbles first to switch backpacks.",
	ItemPurchased = "Item purchased!",
	BackpackEquipped = "Backpack equipped!",
	BackpackUnequipped = "Default backpack equipped.",
	BubbleItems = "BUBBLE ITEMS",
	ItemPotion = "Potion",
	ItemWand = "Wand",
	ItemBoost = "Boost",
	ItemMegaBubble = "Mega Bubble",
	Max = "MAX",
	Denied = "Denied",
	Close = "X",

	-- HUD
	Backpack = "Backpack:",
	BackpackFull = "Backpack full!",
	BackpackAlmostFull = "Backpack almost full",
	RoomAvailable = "Room available",
	Level = "Level",
	BubblesSold = "bubbles sold",
	LevelMax = "MAX",
	GlobalGoal = "Global goal…",
	BubblesUnit = "bubbles",

	-- Portiques / panneaux
	BubbleRoom = "BUBBLE ROOM",
	BackToLobby = "← Lobby",
	ClassicZoneTitle = "CLASSIC ZONE",
	SummerZoneTitle = "SUMMER ZONE",
	SummerZoneUnlocksAt = "UNLOCKS AT LEVEL 5",
	ZoneLockIcon = "🔒",

	-- Notifications
	BackpackFullSell = "Your backpack is full! Go sell your bubbles.",
	BackpackEmpty = "Your backpack is empty, nothing to sell.",
	ProgressReset = "Your progress has been reset.",
	WingsOn = "Wings on — jump to fly!",
	WingsOff = "Wings off.",
	AlreadyOwnWings = "You already own Wings (use the tool to toggle them).",
	WingsUnlocked = "Wings unlocked! Equip the Wings tool, then press RT to toggle them.",
	LegendaryChestAppeared = "⭐ A legendary chest has appeared!",
	ChestSuffix = " chest",
	-- %d = required level, %d = current level, %d = required level
	ZoneLockedFmt = "Reach Level %d to unlock the Summer Zone! Your level: %d / %d",
	-- %s = zone display name
	ZoneUnlockedFmt = "%s unlocked!",
}

return table.freeze(LocalizationStrings)
